In [117]:
import pandas as pd
import numpy as np
from sklearn import linear_model as lm
import pickle

We can open the pickle file to get pandas dataframes that contain the data we need for the states we have chosen to examine.

In [118]:
state_list = ['Washington', 'Georgia', 'New Jersey', 'Utah']
with open('combined_data_dfs.pickle', 'rb') as file:
    combined_data_dfs = pickle.load(file)

Name each pandas dataframe for its state

In [119]:
utah=pd.DataFrame(combined_data_dfs[3])
nj=pd.DataFrame(combined_data_dfs[2])
ga=pd.DataFrame(combined_data_dfs[1])
was=pd.DataFrame(combined_data_dfs[0])

Calculate the mean distancing deviation in the google data for each month. This creates a mean for every county in the state.

In [120]:
feb_distance=[0]*(len(utah["County"]))
for x in range(0,20):
        feb_distance[x]=np.mean(utah.iloc[x,2:17])
        
mar_distance=[0]*(len(utah["County"]))
for x in range(0,20):
        mar_distance[x]=np.mean(utah.iloc[x,17:48])
        
apr_distance=[0]*(len(utah["County"]))
for x in range(0,20):
        apr_distance[x]=np.mean(utah.iloc[x,48:59])

Certain counties have employment in industries marked as (D) which means the number is confidential. Larger numbers
are estimated but smaller ones are not. We simply zero out the field to impute the data. We also append our distance averages to the dataframe.

In [122]:
for x in range(0,20):
    if utah.iloc[x,64]=="(D)":
        utah.iloc[x,64]=0

for x in range(0,20):
    for n in range(67,92):
        if utah.iloc[x,n]=="(D)":
            utah.iloc[x,n]=0

utah['f_dist']=feb_distance
utah['m_dist']=mar_distance
utah['a_dist']=apr_distance

We create measures of percentages for nonfarm jobs and industries hit hard by coronavirus (accomodations, entertainment, transportation, retail).

In [123]:
nonfarm_pct=[0]*(len(utah["County"]))
covid_hit=[0]*(len(utah["County"]))
for x in range(0,20):
        nonfarm_pct[x]=float(utah.iloc[x,65])/float(utah.iloc[x,59])
        covid_hit[x]=(float(utah.iloc[x,83])+float(utah.iloc[x,84])+float(utah.iloc[x,68])+float(utah.iloc[x,73])+float(utah.iloc[x,74]))/float(utah.iloc[x,59])
utah['nfarm']=nonfarm_pct
utah['hosp']=covid_hit

Exo_list is the contains the index of the independent variable that are used in the regression.

In [125]:
exo_list=list()

exo_list.append(1)#Income
exo_list.append(95)#Nonfarm employment
exo_list.append(96)#Covid affected employment


In order to use Scikit's linear regression model, we need to convert the dataframe to a numpy array and change the types
to floats from the original strings.

In [126]:
Y=utah['a_dist'].to_numpy()
X=utah.iloc[:,exo_list].to_numpy()
for i in range(0, len(Y)): 
    Y[i] = float(Y[i])
for i in range(0,len(X[:,1])):
    for n in range(0,len(X[1,:])):
        X[i,n]=float(X[i,n])

Our regression model is as follows:

percent change from baseline work trips = b_0 + b_1 county income (dollars) + b_2 percent nonfarm employment in county + b_3 percent employment in industries with heavy covid impact.

The ouput from the regression includes the R-squared figure and the coefficients of regression.

In [127]:
utah_reg = lm.LinearRegression().fit(X, Y)
print(utah_reg.score(X,Y))
utah_reg.coef_

0.712052348811743


array([-3.24337313e-04, -1.16951612e+02,  1.93306095e+01])

Repeat Process for New Jersey

In [128]:
feb_distance=[0]*(len(nj["County"]))
for x in range(0,19):
        feb_distance[x]=np.mean(nj.iloc[x,2:17])
        
mar_distance=[0]*(len(nj["County"]))
for x in range(0,19):
        mar_distance[x]=np.mean(nj.iloc[x,17:48])
        
apr_distance=[0]*(len(nj["County"]))
for x in range(0,19):
        apr_distance[x]=np.mean(nj.iloc[x,48:59])

for x in range(0,19):
    if nj.iloc[x,64]=="(D)":
        nj.iloc[x,64]=0

for x in range(0,19):
    for n in range(67,92):
        if nj.iloc[x,n]=="(D)":
            nj.iloc[x,n]=0

nj['f_dist']=feb_distance
nj['m_dist']=mar_distance
nj['a_dist']=apr_distance

nonfarm_pct=[0]*(len(nj["County"]))
covid_hit=[0]*(len(nj["County"]))
for x in range(0,19):
        nonfarm_pct[x]=float(nj.iloc[x,65])/float(nj.iloc[x,59])
        covid_hit[x]=(float(nj.iloc[x,83])+float(nj.iloc[x,84])+float(nj.iloc[x,68])+float(nj.iloc[x,73])+float(nj.iloc[x,74]))/float(nj.iloc[x,59])
nj['nfarm']=nonfarm_pct
nj['hosp']=covid_hit

In [129]:
Y=nj['a_dist'].to_numpy()
X=nj.iloc[:,exo_list].to_numpy()
for i in range(0, len(Y)): 
    Y[i] = float(Y[i])
for i in range(0,len(X[:,1])):
    for n in range(0,len(X[1,:])):
        X[i,n]=float(X[i,n])

In [130]:
nj_reg = LinearRegression().fit(X, Y)
print(nj_reg.score(X,Y))
nj_reg.coef_

0.7609575230333342


array([-2.17762575e-04, -3.14017457e+02, -2.88669379e+01])

Repeat Process for Georgia

In [131]:
feb_distance=[0]*(len(ga["County"]))
for x in range(0,138):
        feb_distance[x]=np.mean(ga.iloc[x,2:17])
        
mar_distance=[0]*(len(ga["County"]))
for x in range(0,138):
        mar_distance[x]=np.mean(ga.iloc[x,17:48])
        
apr_distance=[0]*(len(ga["County"]))
for x in range(0,138):
        apr_distance[x]=np.mean(ga.iloc[x,48:59])

for x in range(0,138):
    if ga.iloc[x,64]=="(D)":
        ga.iloc[x,64]=0

for x in range(0,138):
    for n in range(67,92):
        if ga.iloc[x,n]=="(D)":
            ga.iloc[x,n]=0

ga['f_dist']=feb_distance
ga['m_dist']=mar_distance
ga['a_dist']=apr_distance

nonfarm_pct=[0]*(len(ga["County"]))
covid_hit=[0]*(len(ga["County"]))
for x in range(0,138):
        nonfarm_pct[x]=float(ga.iloc[x,65])/float(ga.iloc[x,59])
        covid_hit[x]=(float(ga.iloc[x,83])+float(ga.iloc[x,84])+float(ga.iloc[x,68])+float(ga.iloc[x,73])+float(ga.iloc[x,74]))/float(ga.iloc[x,59])
ga['nfarm']=nonfarm_pct
ga['hosp']=covid_hit

In [132]:
Y=ga['a_dist'].to_numpy()
X=ga.iloc[:,exo_list].to_numpy()
for i in range(0, len(Y)): 
    Y[i] = float(Y[i])
for i in range(0,len(X[:,1])):
    for n in range(0,len(X[1,:])):
        X[i,n]=float(X[i,n])

In [136]:
ga_reg = LinearRegression().fit(X, Y)
print(ga_reg.score(X,Y))
ga_reg.coef_

0.44789574626055306


array([-3.40252555e-04, -5.89051461e+01, -2.33211159e+00])

Repeat Process for Washington

In [138]:
feb_distance=[0]*(len(was["County"]))
for x in range(0,29):
        feb_distance[x]=np.mean(was.iloc[x,2:17])
        
mar_distance=[0]*(len(was["County"]))
for x in range(0,29):
        mar_distance[x]=np.mean(was.iloc[x,17:48])
        
apr_distance=[0]*(len(was["County"]))
for x in range(0,29):
        apr_distance[x]=np.mean(was.iloc[x,48:59])

for x in range(0,29):
    if was.iloc[x,64]=="(D)":
        was.iloc[x,64]=0

for x in range(0,29):
    for n in range(67,92):
        if was.iloc[x,n]=="(D)":
            was.iloc[x,n]=0

was['f_dist']=feb_distance
was['m_dist']=mar_distance
was['a_dist']=apr_distance

nonfarm_pct=[0]*(len(was["County"]))
covid_hit=[0]*(len(was["County"]))
for x in range(0,29):
        nonfarm_pct[x]=float(was.iloc[x,65])/float(was.iloc[x,59])
        covid_hit[x]=(float(was.iloc[x,83])+float(was.iloc[x,84])+float(was.iloc[x,68])+float(was.iloc[x,73])+float(was.iloc[x,74]))/float(was.iloc[x,59])
was['nfarm']=nonfarm_pct
was['hosp']=covid_hit

In [139]:
Y=was['a_dist'].to_numpy()
X=was.iloc[:,exo_list].to_numpy()
for i in range(0, len(Y)): 
    Y[i] = float(Y[i])
for i in range(0,len(X[:,1])):
    for n in range(0,len(X[1,:])):
        X[i,n]=float(X[i,n])

In [141]:
was_reg = LinearRegression().fit(X, Y)
print(was_reg.score(X,Y))
was_reg.coef_

0.5046112183930104


array([-3.67987552e-04, -2.62518864e+01, -8.52556358e+00])